name: ansible-test images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Monday at 08:00 UTC)
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    name: 'Build ansible-test images (${{ matrix.name }} with Python ${{ matrix.python }})'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: archlinux
            python: '3.10'
          - name: centos-stream8
            python: '3.8'
          - name: debian-bullseye
            python: '3.9'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install podman buildah
          pip install ansible-core

      - name: Build ${{ matrix.name }} image
        run: |
          ${{ matrix.name }}/build.sh
        working-directory: ./ansible-test/

      # This is necessary to allow running systemd in rootless containers
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1

      - name: Run basic tests with ${{ matrix.name }} image (latest ansible-core release)
        run: |
          ansible-test integration --color -v --python ${{ matrix.python }} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol

      - name: Install ansible-core devel
        run: |
          pip install https://github.com/ansible/ansible/archive/devel.tar.gz

      - name: Run basic tests with ${{ matrix.name }} image (ansible-core devel)
        run: |
          ansible-test integration --color -v --python ${{ matrix.python }} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol
