name: ansible-test images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Run once per week (Monday at 08:00 UTC)
  schedule:
    - cron: '0 8 * * 1'

jobs:
  build:
    name: 'Build ansible-test images (${{ matrix.name }} with Python ${{ matrix.python }})'
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: archlinux
            python: '3.10'
          - name: centos-stream8
            python: '3.8'
          - name: debian-bullseye
            python: '3.9'

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
          curl -fsSL https://download.opensuse.org/repositories/devel:kubic:libcontainers:unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install podman buildah
          podman info
          pip install ansible-core

      # This is necessary to allow running systemd in rootless containers
      - name: Start systemd user service
        run: |
          loginctl enable-linger runner
          sleep 1

      - name: Build ${{ matrix.name }} image
        run: |
          ${{ matrix.name }}/build.sh
          podman run -td --name ${{ matrix.name }} --systemd=true localhost/test-image:${{ matrix.name }}
          sleep 20
          podman logs ${{ matrix.name }}
          podman kill ${{ matrix.name }}
          podman rm ${{ matrix.name }}
        working-directory: ./ansible-test/

      - name: Run basic tests with ${{ matrix.name }} image (latest ansible-core release)
        run: |
          ansible-test integration --color -v --python ${{ matrix.python }} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol

      - name: Install ansible-core devel
        run: |
          pip install https://github.com/ansible/ansible/archive/devel.tar.gz

      - name: Run basic tests with ${{ matrix.name }} image (ansible-core devel)
        run: |
          ansible-test integration --color -v --python ${{ matrix.python }} --docker localhost/test-image:${{ matrix.name }} shippable/posix/group1/
        env:
          ANSIBLE_TEST_PREFER_PODMAN: 1
        working-directory: ./.github/ansible-test-tests/ansible_collections/testns/testcol
